# -*- coding: utf-8 -*-
from setuptools import setup

modules = \
['_boot',
 '_onewire',
 '_thread',
 '_uasyncio',
 'apa106',
 'array',
 'binascii',
 'bluetooth',
 'btree',
 'cmath',
 'collections',
 'cryptolib',
 'dht',
 'ds18x20',
 'errno',
 'esp',
 'esp32',
 'flashbdev',
 'framebuf',
 'gc',
 'hashlib',
 'heapq',
 'inisetup',
 'io',
 'json',
 'machine',
 'math',
 'micropython',
 'micropython_',
 '__init__',
 'mip',
 'neopixel',
 'network',
 'ntptime',
 'onewire',
 'os',
 'platform',
 'random',
 'select',
 'socket',
 'ssl',
 'struct',
 'sys',
 'time',
 'uarray',
 'core',
 'event',
 'funcs',
 'lock',
 'stream',
 'task',
 'ubinascii',
 'ubluetooth',
 'ucollections',
 'ucryptolib',
 'uctypes',
 'uerrno',
 'uhashlib',
 'uheapq',
 'uio',
 'ujson',
 'umachine',
 'robust',
 'simple',
 'uos',
 'uplatform',
 'upysh',
 'urandom',
 'ure',
 'urequests',
 'uselect',
 'usocket',
 'ussl',
 'ustruct',
 'usys',
 'utime',
 'utimeq',
 'uwebsocket',
 'uzlib',
 'webrepl',
 'webrepl_setup',
 'websocket',
 'zlib']
install_requires = \
['micropython-stdlib-stubs>=0.9.0']

setup_kwargs = {
    'name': 'micropython-esp32-s3-stubs',
    'version': '1.20.0.post1',
    'description': 'MicroPython stubs',
    'long_description': '# micropython-esp32-s3-stubs\n\n\nThis is a stub-only package for MicroPython.\nIt is intended to be installed in a projects virtual environment to allow static type checkers and intellisense features to be used while writing Micropython code.\n\nThe version of this package is alligned the the version of the MicroPython firmware.\n - Major, Minor and Patch levels are alligned to the same version as the firmware.  \n - The post release level is used to publish new releases of the stubs.\n\nFor `Micropython 1.17` the stubs are published as `1.17.post1` ... `1.17.post2`  \nfor `Micropython 1.18` the stubs are published as `1.18.post1` ... `1.18.post2`  \n\nTo install the latest stubs:  \n`pip install -I  micropython-<port>-stubs` where port is the port of the MicroPython firmware.\n\nTo install the stubs for an older version, such as MicroPython 1.17:  \n`pip install micropython-stm32-stubs==1.17.*` which will install the last post release of the stubs for MicroPython 1.17.\n\n\nAs the creation of the stubs, and merging of the different types is still going though improvements, the stub packages are marked as Beta.\nTo upgrade stubs to the latest stubs for a specific version use `pip install micropython-stm32-stubs==1.17.* --upgrade`\n\nIf you have suggestions or find any issues with the stubs, please report them in the [MicroPython-stubs Discussions](https://github.com/Josverl/micropython-stubs/discussions)\n\nFor an overview of  Micropython Stubs please see: https://micropython-stubs.readthedocs.io/en/main/ \n * List of all stubs : https://micropython-stubs.readthedocs.io/en/main/firmware_grp.html\n\nIncluded stubs:\n* Merged stubs from `stubs/micropython-v1_20_0-esp32-s3-merged`\n* Frozen stubs from `stubs/micropython-v1_20_0-frozen/esp32/GENERIC`\n* Core stubs from `stubs/micropython-core`\n\n\norigin | Family | Port | Board | Version\n-------|--------|------|-------|--------\nDocumentation | micropython | - | - | v1.20.0 \nCore | micropython | esp32 | - | v1.20.0 \n',
    'author': 'josverl',
    'author_email': 'josverl@users.noreply.github.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/josverl/micropython-stubs#micropython-stubs',
    'py_modules': modules,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
