# SPDX-License-Identifier: Proprietary
# (c) 2026 SciLabPro. All rights reserved.
# Generated by SciLabPro MicroPad Blocks. Do not hand-edit.
# Source workspace SHA-256: 17aa3cbdcbae8376e803dc81f7691b32d1be0ba82d67320dc28b3c7719062649
# Board profile: titralab_esp32_v1
# Routing profile: titralab_v1_default
import scilabpro as slp
import time

import gc
gc.collect()
from machine import Pin, SPI
from ili9341 import Display, color565
from xglcd_font import XglcdFont
slp.release_tft()
spi = SPI(1, baudrate=40000000, sck=Pin(14), mosi=Pin(13))
display = Display(spi, dc=Pin(27), cs=Pin(15), rst=Pin(0), width=320, height=240, rotation=90)
font = XglcdFont('fonts/EspressoDolce18x24.c', 18, 24)
display.clear(color565(0, 0, 0), hlines=2)


def _tft_row_y(row):
    return 20 + (row - 1) * 34


def _tft_show(row, value):
    if isinstance(value, float):
        text = '{:.1f}'.format(value)
    else:
        text = str(value)
    text = text[:15]
    y = _tft_row_y(row)
    display.fill_rectangle(20, y, 280, 30, color565(0, 0, 0))
    display.draw_text(20, y + 2, text, font, color565(255, 255, 255))


def _tft_clear():
    display.clear(color565(0, 0, 0), hlines=2)


_tft_show(1, 'DS18B20 Temperature')
while True:
    if slp.stop_requested():
        break
    temp = slp.ds18b20(16).read_c()
    print(temp)
    _tft_show(3, temp)
    time.sleep(1)
