# SPDX-License-Identifier: Proprietary
# (c) 2026 SciLabPro. All rights reserved.
# Generated by SciLabPro MicroPad Blocks. Do not hand-edit.
# Source workspace SHA-256: 4f85a81bf587e3d6beee8f8a7747035b6879eaa88a907cda4136c8d7057f63d5
# Board profile: titralab_esp32_v1
# Routing profile: titralab_v1_default
import scilabpro as slp
import time

import gc
gc.collect()
from machine import Pin, SPI
from ili9341 import Display, color565
from xglcd_font import XglcdFont
slp.release_tft()
spi = SPI(1, baudrate=40000000, sck=Pin(14), mosi=Pin(13))
display = Display(spi, dc=Pin(27), cs=Pin(15), rst=Pin(0), width=320, height=240, rotation=90)
font = XglcdFont('fonts/EspressoDolce18x24.c', 18, 24)
display.clear(color565(0, 0, 0), hlines=2)


def _tft_row_y(row):
    return 20 + (row - 1) * 34


def _tft_show_at(x, y, value, decimals=1):
    if isinstance(value, float):
        text = ('{:.' + str(decimals) + 'f}').format(value)
    else:
        text = str(value)
    if x < 0:
        x = 0
    if x > 302:
        x = 302
    if y < 0:
        y = 0
    if y > 210:
        y = 210
    w = 320 - x
    text = text[:w // 18]
    display.fill_rectangle(x, y, w, 30, color565(0, 0, 0))
    display.draw_text(x, y + 2, text, font, color565(255, 255, 255))


def _tft_show(row, value, decimals=1):
    _tft_show_at(20, _tft_row_y(row), value, decimals)


def _tft_clear():
    display.clear(color565(0, 0, 0), hlines=2)


_tft_show(1, 'pH Meter')
while True:
    if slp.stop_requested():
        break
    ph = slp.ph_probe(32).read()
    print(ph)
    _tft_show(3, ph, 2)
    time.sleep(1)
